
export const SET_END_TYPING_STATE = "SET_END_TYPING_STATE";

export const START_NEW_TEXT = "START_NEW_TEXT";

export const CHANGE_INPUT_TEXT = "CHANGE_INPUT_TEXT";

export const CLEAR_TRAINING = "CLEAR_TRAINING";