
export const TRAINING_SET_END_TYPING_STATE = "TRAINING/TRAINING_SET_END_TYPING_STATE";

export const TRAINING_START_NEW_TEXT = "TRAINING/TRAINING_START_NEW_TEXT";

export const TRAINING_CHANGE_INPUT_TEXT = "TRAINING/TRAINING_CHANGE_INPUT_TEXT";

export const TRAINING_CLEAR = "TRAINING/TRAINING_CLEAR";


export const SET_USER = "AUTH/SET_USER";

export const LOGOUT = "AUTH/LOGOUT";


export const SET_LOADING_STATE = "APP/SET_LOADING_STATE"

export const SET_LOADED_STATE = "APP/SET_LOADED_STATE"