
export const SET_USER = "AUTH/SET_USER";

export const LOGOUT = "AUTH/LOGOUT";


export const SET_LOADING_STATE = "APP/SET_LOADING_STATE";

export const SET_LOADED_STATE = "APP/SET_LOADED_STATE";

export const SET_IDLE_STATE = "TRAINING_SPEED/SET_IDLE_STATE";

export const SET_PREPARE_STATE = "TRAINING_SPEED/SET_PREPARE_STATE";

export const SET_TYPING_STATE = "TRAINING_SPEED/SET_TYPING_STATE";

export const SET_END_STATE = "TRAINING_SPEED/SET_END_STATE";

export const SET_ERROR_TYPING = "RAINING_SPEED/SET_ERROR_TYPING";

export const SET_NO_ERROR_TYPING = "RAINING_SPEED/SET_ERROR_TYPING";

export const SET_TEXT = "TRAINING_SPEED/SET_TEXT";

export const SET_SAME_TEXT = "TRAINING_SPEED/SET_SAME_TEXT";

export const SET_INPUT_TEXT = "TRAINING_SPEED/SET_INPUT_TEXT";

export const SET_KEYBOARD_LAYOUT = "TRAINING_SPEED/SET_KEYBOARD_LAYOUT";

export const UPDATE_TIMER = "TRAINING_SPEED/UPDATE_TIMER";