

export const CREATE_ROOM = "GAME/CREATE_ROOM";

export const LEAVE_ROOM = "GAME/LEAVE_ROOM";

export const JOIN_TO_ROOM = "GAME/JOIN_TO_ROOM";

export const SET_ROOM_DATA = "GAME/SET_ROOM_DATA";

export const START_GAME = "GAME/START_GAME";

export const START_SINGLE_GAME = "GAME/START_SINGLE_GAME";

export const SET_IDLE_STATE = "GAME/SET_IDLE_STATE";

export const SET_PREPARE_STATE = "GAME/SET_PREPARE_STATE";

export const SET_TYPING_STATE = "GAME/SET_TYPING_STATE";

export const SET_END_STATE = "GAME/SET_END_STATE";

export const SET_END_DATA = "GAME/SET_END_DATA";

export const SET_INPUT_TEXT = "GAME/SET_INPUT_TEXT";

export const SET_ROOM_ERROR = "GAME/SET_ROOM_ERROR";

export const UPDATE_ROOM = "GAME/UPDATE_ROOM";

export const SET_ROOM_OWNER = "GAME/SET_ROOM_OWNER";