
export const SET_IDLE_STATE = "TRAINING_SPEED/SET_IDLE_STATE";

export const SET_PREPARE_STATE = "TRAINING_SPEED/SET_PREPARE_STATE";

export const SET_TYPING_STATE = "TRAINING_SPEED/SET_TYPING_STATE";

export const SET_END_STATE = "TRAINING_SPEED/SET_END_STATE";

export const SET_ERROR_TYPING = "RAINING_SPEED/SET_ERROR_TYPING";

export const SET_NO_ERROR_TYPING = "RAINING_SPEED/SET_ERROR_TYPING";

export const SET_INPUT_TEXT = "TRAINING_SPEED/SET_INPUT_TEXT";

export const UPDATE_TIMER = "TRAINING_SPEED/UPDATE_TIMER";

export const SET_ROOM_ID = "TRAINING_SPEED/SET_ROOM_ID";